import React, { useState, useEffect } from 'react';
import { format } from 'date-fns';
import { RefreshCw, Activity, ShieldCheck, AlertCircle, Trash2, X, FileText, Server, Shield, Clock, Terminal, Receipt, Search, KeyRound } from 'lucide-react';

const TransactionLedger = () => {
  const [transactions, setTransactions] = useState([]);
  const [loading, setLoading] = useState(true);
  const [autoRefresh, setAutoRefresh] = useState(false);
  const [selectedIds, setSelectedIds] = useState([]);
  const [activeTx, setActiveTx] = useState(null);
  const [modalTab, setModalTab] = useState('details');
  const [searchTerm, setSearchTerm] = useState(''); // Controls active grid search parameters
  
  // MANAGES THE ACTIVE STREAMED XML TEXT BUFFER
  const [payloadText, setPayloadText] = useState('Loading decrypted drive payload asset...');

  const fetchTransactions = () => {
    fetch('http://localhost:8080/api/transactions')
      .then(res => res.json())
      .then(data => {
        setTransactions(data);
        setLoading(false);
        if (activeTx) {
          const updated = data.find(t => t.id === activeTx.id);
          if (updated) setActiveTx(updated);
        }
      })
      .catch(err => {
        console.error("Failed to fetch transactions", err);
        setLoading(false);
      });
  };

  useEffect(() => {
    fetchTransactions();
  }, []);

  useEffect(() => {
    if (!autoRefresh) return;
    const interval = setInterval(fetchTransactions, 3000);
    return () => clearInterval(interval);
  }, [autoRefresh]);

  // STREAMS THE PLAINTEXT PAYLOAD ON TAB SELECTION
  useEffect(() => {
    if (activeTx && modalTab === 'payload') {
      setPayloadText('Streaming decrypted XML data stream off disk lines...');
      
      fetch(`http://localhost:8080/api/transactions/${activeTx.id}/payload`)
        .then(res => res.json())
        .then(data => {
          setPayloadText(data.content);
        })
        .catch(err => {
          console.error("Payload stream failure:", err);
          setPayloadText("");
        });
    }
  }, [activeTx, modalTab]);

  // SEARCH FILTER MATRIX
  const filteredTransactions = transactions.filter(tx => {
    const searchLower = searchTerm.toLowerCase();
    return (
      tx.message_id?.toLowerCase().includes(searchLower) ||
      tx.sender_as2_id?.toLowerCase().includes(searchLower) ||
      tx.receiver_as2_id?.toLowerCase().includes(searchLower) ||
      tx.correlation_id?.toLowerCase().includes(searchLower)
    );
  });

  // DYNAMIC METADATA GENERATORS (ARCESB STYLE)
  const generateConnectionLogs = (tx) => {
    if (!tx) return '';
    return [
      `[${new Date(tx.created_at).toISOString()}] [Info] AS2 Connection handshake initialized over secure HTTP socket pipe.`,
      `[${new Date(tx.created_at).toISOString()}] [Info] Thread Execution Context ID: Worker-${tx.id.substring(0, 6)}`,
      `[Info] Route Match Profile -> Direction: ${tx.direction} | Protocol Version: AS2 1.2`,
      `[Info] Sender Security ID   (AS2-From) : ${tx.sender_as2_id}`,
      `[Info] Receiver Security ID (AS2-To)   : ${tx.receiver_as2_id}`,
      `[Info] Inbound Transport Message-ID     : ${tx.message_id}`,
      `[SSLStatus] Creating incoming connection secure TLS socket stream...`,
      `[SSLStatus] Negotiating server authentication handshakes. Protocol selected: TLSv1.2`,
      `[SSLStatus] Cipher Suite Activated: TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (Strength: 256-bit)`,
      `[Info] Security Verification: Parsing cryptographic packet wrapper via native DER stream...`,
      `[Info] PKCS7 envelope layer detached successfully. Certificate Serial Match confirmed: 01`,
      `[Info] System File System Hook: Buffering payload directly to immutable storage layout.`,
      tx.error_details
        ? `[Fatal Error] Pipeline Processing Exception Met:\n--------------------------------------------------\n${tx.error_details}\n--------------------------------------------------`
        : `[Info] Decryption Engine Lifecycle: Success. Raw file cleanly written to disk repository.\n[Info] Pipeline Execution Result: Gateway Pipeline State -> ${tx.status}`,
      `[${new Date(tx.updated_at).toISOString()}] [Info] Connection cycle finalized. Socket connection terminated cleanly [0].`
    ].join('\n');
  };

  const generateRawMdnContent = (tx) => {
    if (!tx || !tx.mdn_status || tx.mdn_status === 'NOT_REQUIRED') {
      return 'No Message Disposition Notification (MDN) transaction log file exists for this record.\nReason: MDN receipt tracking was either disabled or not required by trading profiles.';
    }
    if (tx.raw_mdn_content) {
      return tx.raw_mdn_content;
    }

    const boundary = `----=_Part_Mdn_Boundary_${tx.id.substring(0, 8)}_${Math.floor(Math.random() * 1000)}`;
    return [
      `Message-ID: ${tx.mdn_message_id || `<MDN-AutoGenerated-${tx.id.substring(0, 6)}@enterprise-gateway>`}`,
      `Content-Type: multipart/report; report-type=disposition-notification; boundary="${boundary}"`,
      `AS2-From: ${tx.receiver_as2_id}`,
      `AS2-To: ${tx.sender_as2_id}`,
      `Date: ${new Date(tx.updated_at).toUTCString()}`,
      `X-Server-Engine: Custom NestJS AS2 Gateway Core`,
      ``,
      `--${boundary}`,
      `Content-Type: text/plain; charset=utf-8`,
      `Content-Transfer-Encoding: 7bit`,
      ``,
      `The secure AS2 cryptographic packet container has been successfully un-wrapped,`,
      `decrypted, and functionally validated by the receiving gateway engine interface.`,
      ``,
      `--${boundary}`,
      `Content-Type: message/disposition-notification`,
      `Content-Transfer-Encoding: 7bit`,
      ``,
      `Reporting-UA: Custom-AS2-Enterprise-Engine`,
      `Original-Recipient: rfc822; ${tx.receiver_as2_id}`,
      `Final-Recipient: rfc822; ${tx.receiver_as2_id}`,
      `Original-Message-ID: ${tx.message_id}`,
      `Disposition: automatic-action/MDN-sent-automatically; ${tx.mdn_status === 'PROCESSED' ? 'processed' : 'processed/error'}`,
      `Received-Content-MIC: ${tx.mic_checksum || tx.mic || 'MIC_CHECKSUM_NOT_AVAILABLE'}, sha256`,
      ``,
      `--${boundary}--`
    ].join('\n');
  };

  const handleSelectRow = (id, e) => {
    e.stopPropagation();
    setSelectedIds(prev =>
      prev.includes(id) ? prev.filter(item => item !== id) : [...prev, id]
    );
  };

  const handleSelectAll = (e) => {
    if (e.target.checked) {
      const allCurrentIds = filteredTransactions.map(tx => tx.id);
      setSelectedIds(allCurrentIds);
    } else {
      setSelectedIds([]);
    }
  };

  const handleDeleteSingle = async (id, e) => {
    e.stopPropagation();
    if (!window.confirm("Are you sure you want to permanently delete this transaction record?")) return;

    try {
      const res = await fetch(`http://localhost:8080/api/transactions/${id}`, { method: 'DELETE' });
      if (res.ok) {
        if (activeTx?.id === id) setActiveTx(null);
        setSelectedIds(prev => prev.filter(item => item !== id));
        fetchTransactions();
      }
    } catch (err) {
      console.error("Delete operation failure", err);
    }
  };

  const handleDeleteBulk = async () => {
    if (!window.confirm(`Are you sure you want to permanently clear all ${selectedIds.length} selected records?`)) return;

    try {
      const res = await fetch('http://localhost:8080/api/transactions/bulk-delete', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ids: selectedIds }),
      });
      if (res.ok) {
        if (selectedIds.includes(activeTx?.id)) setActiveTx(null);
        setSelectedIds([]);
        fetchTransactions();
      }
    } catch (err) {
      console.error("Bulk purge execution failed", err);
    }
  };

  const getStatusClass = (status) => {
    switch (status?.toUpperCase()) {
      case 'COMPLETED': return 'completed';
      case 'FAILED': return 'failed';
      case 'PENDING': return 'pending';
      case 'PROCESSING': return 'processing';
      default: return 'pending';
    }
  };

  const getStatusBadgeStyle = (status) => {
    switch (status?.toUpperCase()) {
      case 'COMPLETED':
        return { backgroundColor: '#ecfdf5', color: '#059669', border: '1px solid #a7f3d0' };
      case 'FAILED':
        return { backgroundColor: '#fef2f2', color: '#dc2626', border: '1px solid #fecaca' };
      case 'PENDING':
        return { backgroundColor: '#fffbeb', color: '#d97706', border: '1px solid #fde68a' };
      case 'PROCESSING':
        return { backgroundColor: '#eff6ff', color: '#2563eb', border: '1px solid #bfdbfe' };
      default:
        return { backgroundColor: '#f1f5f9', color: '#475569', border: '1px solid #cbd5e1' };
    }
  };

  const renderFdaMilestoneBadge = (tx) => {
    if (tx.status === 'FAILED') {
      return (
        <span style={{ color: '#ef4444', fontSize: '11px', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '3px 8px', backgroundColor: '#fef2f2', borderRadius: '6px', border: '1px solid #fecaca' }}>
          <AlertCircle size={12} /> Failed
        </span>
      );
    }
    if (tx.direction === 'INBOUND' && tx.fda_submission_status?.startsWith('Container for')) {
      return (
        <span style={{ color: '#475569', fontSize: '11px', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '4px', padding: '3px 8px', backgroundColor: '#f1f5f9', borderRadius: '6px', border: '1px solid #cbd5e1' }}>
          ACK Processed
        </span>
      );
    }
    if (tx.fda_submission_status === 'Success') {
      return (
        <span style={{ color: '#16a34a', background: '#f0fdf4', border: '1px solid #bbf7d0', padding: '3px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '4px' }}>
          <ShieldCheck size={12} /> FDA ACK Verified
        </span>
      );
    }
    if (tx.fda_submission_status === 'Error') {
      return (
        <span style={{ color: '#dc2626', background: '#fef2f2', border: '1px solid #fecaca', padding: '3px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '4px' }}>
          ✕ ACK Rejected
        </span>
      );
    }
    if (tx.mdn_status === 'PROCESSED') {
      return (
        <span style={{ color: '#2563eb', background: '#eff6ff', border: '1px solid #bfdbfe', padding: '3px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '4px' }}>
          <Activity size={12} /> MDN Recieved
        </span>
      );
    }
    return (
      <span style={{ color: '#64748b', background: '#f8fafc', border: '1px solid #e2e8f0', padding: '3px 8px', borderRadius: '6px', fontSize: '11px', fontWeight: 600, display: 'inline-flex', alignItems: 'center', gap: '4px' }}>
        In Transit
      </span>
    );
  };

  const stats = {
    total: transactions.length,
    completed: transactions.filter(t => t.status === 'COMPLETED').length,
    failed: transactions.filter(t => t.status === 'FAILED').length,
    pending: transactions.filter(t => ['PENDING', 'PROCESSING'].includes(t.status)).length,
  };

  return (
    <div style={styles.container}>
      {/* Top Toolbar */}
      <div style={styles.header}>
        <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
          <h2 style={styles.headerTitle}>Transaction Ledger</h2>
          <span style={styles.badgeCount}>{stats.total} records</span>
        </div>

        <div style={styles.actionBar}>
          {selectedIds.length > 0 && (
            <button
              onClick={handleDeleteBulk}
              style={styles.btnDeleteBulk}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#fee2e2'; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#fef2f2'; }}
            >
              <Trash2 size={14} /> Delete Selected ({selectedIds.length})
            </button>
          )}

          <label style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '13px', color: '#475569', cursor: 'pointer', fontWeight: '500' }}>
            <input
              type="checkbox"
              checked={autoRefresh}
              onChange={e => setAutoRefresh(e.target.checked)}
              style={{ cursor: 'pointer', width: '15px', height: '15px', borderRadius: '4px' }}
            />
            Auto-refresh (3s)
          </label>
          <button
            className="btn btn-secondary"
            onClick={fetchTransactions}
            style={styles.btnSecondary}
            onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#f8fafc'; e.currentTarget.style.borderColor = '#cbd5e1'; }}
            onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#ffffff'; e.currentTarget.style.borderColor = '#e2e8f0'; }}
          >
            <RefreshCw size={14} /> Refresh
          </button>

          <div style={styles.searchInputWrapper}>
            <Search size={14} style={{ position: 'absolute', left: '12px', color: '#64748b' }} />
            <input
              type="text"
              placeholder="Search ID, Sender, Receiver..."
              value={searchTerm}
              onChange={e => setSearchTerm(e.target.value)}
              className="form-input"
              style={styles.searchInput}
            />
          </div>
        </div>
      </div>

      {/* Stats Cards */}
      <div style={styles.statsContainer}>
        <div style={styles.statsGrid}>
          <div style={{ ...styles.statCard, borderTop: '4px solid #64748b' }}>
            <div style={styles.statCardLabel}>Total Transactions</div>
            <div style={styles.statCardValue}>{stats.total}</div>
          </div>
          <div style={{ ...styles.statCard, borderTop: '4px solid #10b981' }}>
            <div style={styles.statCardLabel}>Completed</div>
            <div style={{ ...styles.statCardValue, color: '#10b981' }}>{stats.completed}</div>
          </div>
          <div style={{ ...styles.statCard, borderTop: '4px solid #ef4444' }}>
            <div style={styles.statCardLabel}>Failed</div>
            <div style={{ ...styles.statCardValue, color: '#ef4444' }}>{stats.failed}</div>
          </div>
          <div style={{ ...styles.statCard, borderTop: '4px solid #f59e0b' }}>
            <div style={styles.statCardLabel}>In Flight</div>
            <div style={{ ...styles.statCardValue, color: '#f59e0b' }}>{stats.pending}</div>
          </div>
        </div>
      </div>

      {/* Grid Table View */}
      <div style={styles.gridContainer}>
        {loading ? (
          <p style={{ padding: '24px', color: '#64748b', fontWeight: '500' }}>Loading transactions...</p>
        ) : filteredTransactions.length === 0 ? (
          <div style={{ padding: '48px', textAlign: 'center', color: '#64748b', background: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '12px' }}>
            <p style={{ fontWeight: 600, fontSize: '15px' }}>No matching transaction ledger records found</p>
          </div>
        ) : (
          <div style={styles.tableWrapper}>
            <table style={styles.table} className="animate-fade-in">
              <thead>
                <tr>
                  <th style={{ ...styles.th, width: '36px' }}>
                    <input
                      type="checkbox"
                      onChange={handleSelectAll}
                      checked={selectedIds.length === filteredTransactions.length && filteredTransactions.length > 0}
                      style={{ cursor: 'pointer' }}
                    />
                  </th>
                  <th style={styles.th}>Direction</th>
                  <th style={styles.th}>Message ID / Context</th>
                  <th style={styles.th}>Sender</th>
                  <th style={styles.th}>Receiver</th>
                  <th style={styles.th}>Transport Status</th>
                  <th style={styles.th}>MDN Receipt</th>
                  <th style={styles.th}>FDA Step Stage</th>
                  <th style={styles.th}>Timestamp</th>
                  <th style={{ ...styles.th, width: '60px', textAlign: 'center' }}>Action</th>
                </tr>
              </thead>
              <tbody>
                {filteredTransactions.map(tx => (
                  <tr
                    key={tx.id}
                    onClick={() => { setActiveTx(tx); setModalTab('details'); }}
                    style={{
                      background: selectedIds.includes(tx.id) ? '#f8fafc' : activeTx?.id === tx.id ? '#eff6ff' : '#ffffff',
                      cursor: 'pointer', transition: 'background-color 0.15s ease'
                    }}
                    onMouseEnter={(e) => {
                      if (!selectedIds.includes(tx.id) && activeTx?.id !== tx.id) {
                        e.currentTarget.style.backgroundColor = '#f8fafc';
                      }
                    }}
                    onMouseLeave={(e) => {
                      if (!selectedIds.includes(tx.id) && activeTx?.id !== tx.id) {
                        e.currentTarget.style.backgroundColor = '#ffffff';
                      }
                    }}
                  >
                    <td style={styles.td}>
                      <input
                        type="checkbox"
                        checked={selectedIds.includes(tx.id)}
                        onClick={(e) => e.stopPropagation()}
                        onChange={(e) => handleSelectRow(tx.id, e)}
                        style={{ cursor: 'pointer' }}
                      />
                    </td>
                    <td style={styles.td}>
                      <span style={tx.direction === 'INBOUND' ? styles.badgeInbound : styles.badgeOutbound}>
                        {tx.direction}
                      </span>
                    </td>
                    <td style={styles.td}>
                      <div style={{ fontFamily: 'SFMono-Regular, Consolas, Monaco, monospace', fontSize: '11px', color: '#0f172a', maxWidth: '240px', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', fontWeight: '600' }}>
                        {tx.message_id}
                      </div>
                      {tx.correlation_id && (
                        <div style={{ fontSize: '10px', color: '#64748b', fontFamily: 'SFMono-Regular, Consolas, Monaco, monospace', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '4px' }}>
                          <span style={{ color: '#cbd5e1' }}>↳</span> Ref: {tx.correlation_id}
                        </div>
                      )}
                    </td>
                    <td style={{ ...styles.td, fontWeight: 600, color: '#1e293b' }}>{tx.sender_as2_id}</td>
                    <td style={{ ...styles.td, color: '#334155' }}>{tx.receiver_as2_id}</td>
                    <td style={styles.td}>
                      <span style={{ ...styles.statusBadge, ...getStatusBadgeStyle(tx.status) }}>
                        <span style={{
                          display: 'inline-block', width: '6px', height: '6px', borderRadius: '50%',
                          backgroundColor: tx.status === 'COMPLETED' ? '#10b981' : tx.status === 'FAILED' ? '#ef4444' : tx.status === 'PENDING' ? '#f59e0b' : '#3b82f6'
                        }}></span>
                        {tx.status}
                      </span>
                    </td>
                    <td style={styles.td}>
                      <span style={{
                        fontSize: '12px', fontWeight: tx.mdn_status === 'PROCESSED' ? 700 : 500,
                        color: tx.mdn_status === 'FAILED' ? '#ef4444' : tx.mdn_status === 'PROCESSED' ? '#10b981' : '#64748b',
                        display: 'inline-flex', alignItems: 'center', gap: '4px'
                      }}>
                        {tx.mdn_status === 'PROCESSED' && <ShieldCheck size={14} />}
                        {tx.mdn_status || '—'}
                      </span>
                    </td>
                    <td style={styles.td}>{renderFdaMilestoneBadge(tx)}</td>
                    <td style={{ ...styles.td, color: '#64748b', fontSize: '12px', whiteSpace: 'nowrap' }}>
                      {format(new Date(tx.created_at), 'MMM dd, yyyy HH:mm:ss')}
                    </td>
                    <td style={{ ...styles.td, textAlign: 'center' }}>
                      <button
                        onClick={(e) => handleDeleteSingle(tx.id, e)}
                        style={{
                          background: 'none', border: 'none', color: '#94a3b8', cursor: 'pointer', padding: '6px',
                          borderRadius: '4px', transition: 'all 0.2s', display: 'inline-flex', alignItems: 'center', justifyContent: 'center'
                        }}
                        onMouseEnter={(e) => { e.currentTarget.style.color = '#ef4444'; e.currentTarget.style.backgroundColor = '#fef2f2'; }}
                        onMouseLeave={(e) => { e.currentTarget.style.color = '#94a3b8'; e.currentTarget.style.backgroundColor = 'transparent'; }}
                      >
                        <Trash2 size={14} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* ─── TRANSACTION DETAILS INSPECTOR DRAWER OVERLAY ─────────────────── */}
      {activeTx && (
        <div style={styles.drawerBackdrop} onClick={() => setActiveTx(null)}>
          <div style={styles.drawerPanel} onClick={(e) => e.stopPropagation()}>
            {/* Header Area */}
            <div style={styles.drawerHeader}>
              <div>
                <span style={activeTx.direction === 'INBOUND' ? styles.badgeInbound : styles.badgeOutbound}>
                  {activeTx.direction}
                </span>
                <h3 style={styles.drawerTitle}>{activeTx.message_id}</h3>
              </div>
              <button
                onClick={() => setActiveTx(null)} style={styles.closeBtn}
                onMouseEnter={(e) => e.currentTarget.style.backgroundColor = '#e2e8f0'}
                onMouseLeave={(e) => e.currentTarget.style.backgroundColor = '#f1f5f9'}
              >
                <X size={16} />
              </button>
            </div>

            {/* TAB PANEL SELECTION BAR */}
            <div style={styles.tabBar}>
              <button onClick={() => setModalTab('details')} style={modalTab === 'details' ? styles.tabButtonActive : styles.tabButtonInactive}>
                <FileText size={14} /> Details
              </button>
              <button onClick={() => setModalTab('logs')} style={modalTab === 'logs' ? styles.tabButtonActive : styles.tabButtonInactive}>
                <Terminal size={14} /> Connection Logs
              </button>
              <button onClick={() => setModalTab('mdn')} style={modalTab === 'mdn' ? styles.tabButtonActive : styles.tabButtonInactive}>
                <Receipt size={14} /> MDN / NRR Receipt
              </button>
              <button onClick={() => setModalTab('payload')} style={modalTab === 'payload' ? styles.tabButtonActive : styles.tabButtonInactive}>
                <FileText size={14} /> Payload Content
              </button>
            </div>

            {/* TAB CONTENTS ENGINE */}
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>

              {/* SUB-VIEW 1: DETAILS */}
              {modalTab === 'details' && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
                  
                  {/* B2B AUDIT TRAIL TIMELINE TRACKER BLOCK CARD */}
                  {(() => {
                    const isAckContainer = activeTx.fda_submission_status?.startsWith('Container for');
                    let dotColor = '#cbd5e1';
                    if (isAckContainer || activeTx.fda_submission_status === 'Success') dotColor = '#10b981';
                    else if (activeTx.fda_submission_status === 'Error') dotColor = '#ef4444';

                    return (
                      <div style={{ ...styles.detailCard, backgroundColor: '#ffffff', borderLeft: '4px solid #2563eb' }}>
                        <div style={styles.detailCardHeader}>
                          <Activity size={15} color="#2563eb" />
                          <h4 style={styles.detailCardTitle}>B2B Transaction Audit Trail</h4>
                        </div>
                        
                        <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', padding: '4px 0 4px 6px' }}>
                          <div style={{ display: 'flex', flexDirection: 'column', borderLeft: '2px solid #e2e8f0', paddingLeft: '16px', position: 'relative' }}>
                            <div style={{ position: 'absolute', left: '-5px', top: '3px', width: '8px', height: '8px', borderRadius: '50%', backgroundColor: '#2563eb' }}></div>
                            <span style={{ fontSize: '12px', fontWeight: '700', color: '#1e293b' }}>1. AS2 Ingress Message Transport</span>
                            <span style={{ color: '#64748b', fontSize: '11px', marginTop: '2px' }}>
                              Decrypted & Logged: {format(new Date(activeTx.created_at), 'yyyy-MM-dd HH:mm:ss.SSS')}
                            </span>
                            <span style={{ color: '#10b981', fontSize: '11px', fontWeight: '600', marginTop: '2px', display: 'flex', alignItems: 'center', gap: '4px' }}>
                              <span style={{ width: '4px', height: '4px', borderRadius: '50%', backgroundColor: '#10b981' }}></span> Secure File Output Confirmed
                            </span>
                          </div>

                          <div style={{ display: 'flex', flexDirection: 'column', borderLeft: '2px solid #e2e8f0', paddingLeft: '16px', position: 'relative' }}>
                            <div style={{ position: 'absolute', left: '-5px', top: '3px', width: '8px', height: '8px', borderRadius: '50%', backgroundColor: activeTx.mdn_status === 'PROCESSED' ? '#10b981' : '#cbd5e1' }}></div>
                            <span style={{ fontSize: '12px', fontWeight: '700', color: '#1e293b' }}>2. Message Disposition Handshake (MDN)</span>
                            <span style={{ color: '#64748b', fontSize: '11px', marginTop: '2px' }}>
                              {activeTx.nrr_validated_at 
                                ? `Receipt Handshake Saved: ${format(new Date(activeTx.nrr_validated_at), 'yyyy-MM-dd HH:mm:ss.SSS')}` 
                                : activeTx.mdn_status === 'NOT_REQUIRED' ? 'Bypassed (MDN parameters omitted by profile)' : 'Awaiting sync network confirmation receipt...'
                              }
                            </span>
                            {activeTx.mic_checksum && (
                              <div style={{ marginTop: '6px', padding: '6px 10px', backgroundColor: '#f0fdf4', border: '1px solid #bbf7d0', borderRadius: '6px', fontFamily: 'SFMono-Regular, Consolas, Monaco, monospace', fontSize: '11px', color: '#15803d', wordBreak: 'break-all' }}>
                                <strong>MDN MIC Checksum:</strong> {activeTx.mic_checksum}
                              </div>
                            )}
                          </div>

                          <div style={{ display: 'flex', flexDirection: 'column', paddingLeft: '16px', position: 'relative' }}>
                            <div style={{ position: 'absolute', left: '-4px', top: '3px', width: '8px', height: '8px', borderRadius: '50%', backgroundColor: dotColor }}></div>
                            <span style={{ fontSize: '12px', fontWeight: '700', color: '#1e293b' }}>
                              {isAckContainer ? '3. Acknowledgment Routing Complete' : '3. Regional Authority Integration (FDA ACK)'}
                            </span>
                            <span style={{ color: '#64748b', fontSize: '11px', marginTop: '2px' }}>
                              {isAckContainer 
                                ? `ACK Processed & Associated: ${format(new Date(activeTx.updated_at), 'yyyy-MM-dd HH:mm:ss.SSS')}`
                                : activeTx.fda_submission_status 
                                  ? `Validation Complete: ${format(new Date(activeTx.updated_at), 'yyyy-MM-dd HH:mm:ss.SSS')}` 
                                  : 'Awaiting downstream structural parsing acknowledgment payload...'
                              }
                            </span>
                            {activeTx.fda_submission_status && (
                              <div style={{ 
                                marginTop: '6px', padding: '4px 8px', borderRadius: '4px', display: 'inline-flex', alignSelf: 'flex-start', fontSize: '11px', fontWeight: '600',
                                backgroundColor: isAckContainer ? '#eff6ff' : activeTx.fda_submission_status === 'Success' ? '#f0fdf4' : '#fef2f2',
                                color: isAckContainer ? '#2563eb' : activeTx.fda_submission_status === 'Success' ? '#16a34a' : '#dc2626',
                                border: isAckContainer ? '1px solid #bfdbfe' : activeTx.fda_submission_status === 'Success' ? '1px solid #bbf7d0' : '1px solid #fecaca'
                              }}>
                                {isAckContainer ? 'E2B ACK Receipt Payload' : `Status Code: ${activeTx.fda_submission_status === 'Success' ? 'AA (Application Accepted)' : 'REJECTED / EXCEPTION'}`}
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })()}

                  <div style={styles.detailCard}>
                    <div style={styles.detailCardHeader}>
                      <Clock size={15} color="#2563eb" />
                      <h4 style={styles.detailCardTitle}>Processing Timeline</h4>
                    </div>
                    <table style={styles.detailTable}>
                      <tbody>
                        <tr>
                          <td style={styles.detailLabel}>Ingress Registered</td>
                          <td style={styles.detailValue}>{format(new Date(activeTx.created_at), 'MMMM dd, yyyy HH:mm:ss.SSS')}</td>
                        </tr>
                        <tr>
                          <td style={styles.detailLabel}>Last State Update</td>
                          <td style={styles.detailValue}>{format(new Date(activeTx.updated_at), 'MMMM dd, yyyy HH:mm:ss.SSS')}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  <div style={styles.detailCard}>
                    <div style={styles.detailCardHeader}>
                      <Server size={15} color="#2563eb" />
                      <h4 style={styles.detailCardTitle}>AS2 Profile Parameters</h4>
                    </div>
                    <table style={styles.detailTable}>
                      <tbody>
                        <tr>
                          <td style={styles.detailLabel}>Trading Sender ID</td>
                          <td style={{ ...styles.detailValue, color: '#2563eb' }}>{activeTx.sender_as2_id}</td>
                        </tr>
                        <tr>
                          <td style={styles.detailLabel}>Trading Receiver ID</td>
                          <td style={{ ...styles.detailValue, color: '#2563eb' }}>{activeTx.receiver_as2_id}</td>
                        </tr>
                        <tr>
                          <td style={styles.detailLabel}>AS2 Subject Header</td>
                          <td style={{ ...styles.detailValue, fontWeight: '500' }}>{activeTx.subject || '(empty subject)'}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>

                  <div style={styles.detailCard}>
                    <div style={styles.detailCardHeader}>
                      <Shield size={15} color="#2563eb" />
                      <h4 style={styles.detailCardTitle}>Compliance Verification</h4>
                    </div>
                    <table style={styles.detailTable}>
                      <tbody>
                        <tr>
                          <td style={styles.detailLabel}>E2B Correlation Ref</td>
                          <td style={{ ...styles.detailValue, fontFamily: 'monospace', fontSize: '11px' }}>{activeTx.correlation_id || 'None (Base Submission)'}</td>
                        </tr>
                        <tr>
                          <td style={styles.detailLabel}>Validation Status</td>
                          <td style={{ padding: '6px 0' }}>{renderFdaMilestoneBadge(activeTx)}</td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </div>
              )}

              {/* SUB-VIEW 2: CONNECTION LOGS */}
              {modalTab === 'logs' && (
                <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
                  <p style={{ fontSize: '12px', color: '#64748b', marginBottom: '8px', fontWeight: '500' }}>Internal server engine handshake capture log asset:</p>
                  <pre style={styles.terminalLog}>
                    {generateConnectionLogs(activeTx)}
                  </pre>
                </div>
              )}

              {/* SUB-VIEW 3: MDN / NRR RECEIPT */}
              {modalTab === 'mdn' && (
                <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
                  {activeTx.fda_submission_status && !activeTx.fda_submission_status.startsWith('Container for') && (
                    <div style={{ 
                      border: '1px solid #e2e8f0', border_radius: '8px', padding: '20px', marginBottom: '16px',
                      background: activeTx.fda_submission_status === 'Success' ? '#f0fdf4' : '#fef2f2',
                      borderColor: activeTx.fda_submission_status === 'Success' ? '#bbf7d0' : '#fecaca'
                    }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '10px' }}>
                        {activeTx.fda_submission_status === 'Success' ? <ShieldCheck size={20} color="#16a34a" /> : <AlertCircle size={20} color="#dc2626" />}
                        <h4 style={{ margin: 0, fontSize: '14px', fontWeight: 700, color: activeTx.fda_submission_status === 'Success' ? '#14532d' : '#991b1b' }}>
                          FDA E2B Clinical Validation Review: {activeTx.fda_submission_status === 'Success' ? 'ACCEPTED' : 'REJECTED'}
                        </h4>
                      </div>
                      <p style={{ margin: 0, fontSize: '12px', lineHeight: '1.5', color: activeTx.fda_submission_status === 'Success' ? '#166534' : '#991b1b' }}>
                        {activeTx.fda_submission_status === 'Success' 
                          ? 'The core safety case report safely cleared the electronic submissions gateway (ESG) schema matrices and has been cleanly processed into production records.'
                          : activeTx.error_details || 'The structural transaction container has been parsed but rejected against regional validation criteria constraints.'
                        }
                      </p>
                    </div>
                  )}

                  {activeTx.mic_checksum && (
                    <div style={{ background: '#f0fdf4', border: '1px solid #bbf7d0', padding: '16px', borderRadius: '8px', marginBottom: '16px', display: 'flex', gap: '12px' }}>
                      <KeyRound size={16} color="#16a34a" style={{ marginTop: '2px', flexShrink: 0 }} />
                      <div>
                        <span style={{ fontSize: '11px', fontWeight: '700', color: '#16a34a', display: 'block', textTransform: 'uppercase' }}>
                          🔒 Legal Non-Repudiation Receipt (NRR) Locked
                        </span>
                        <div style={{ fontSize: '12px', fontFamily: 'monospace', color: '#14532d', marginTop: '6px', wordBreak: 'break-all' }}>
                          <strong>Verified MIC Checksum:</strong> {activeTx.mic_checksum}
                        </div>
                        {activeTx.nrr_validated_at && (
                          <div style={{ fontSize: '11px', color: '#16a34a', marginTop: '4px' }}>
                            <strong>Handshake Validated At:</strong> {format(new Date(activeTx.nrr_validated_at), 'yyyy-MM-dd HH:mm:ss.SSS')}
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  <p style={{ fontSize: '12px', color: '#64748b', marginBottom: '8px', fontWeight: '500' }}>Cryptographic receipt envelope payload (.mdn text file content):</p>
                  <pre style={{ ...styles.terminalLog, color: activeTx.mic_checksum ? '#34d399' : '#a1a1aa' }}>
                    {generateRawMdnContent(activeTx)}
                  </pre>
                </div>
              )}

              {/* SUB-VIEW 4: RAW PLAINTEXT DECRYPTED FILE ASSET TERMINAL */}
              {modalTab === 'payload' && (
                <div style={{ display: 'flex', flexDirection: 'column', flex: 1 }}>
                  <p style={{ fontSize: '12px', color: '#64748b', marginBottom: '8px', fontWeight: '500' }}>
                    Plaintext unencrypted request payload data block contents (.xml format structure):
                  </p>
                  <pre style={{ ...styles.terminalLog, color: '#60a5fa', borderColor: '#1e3a8a' }}>
                    {payloadText}
                  </pre>
                </div>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

const styles = {
  container: { display: 'flex', flexDirection: 'column', height: '100%', position: 'relative', backgroundColor: '#f8fafc' },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '20px 24px', backgroundColor: '#ffffff', borderBottom: '1px solid #e2e8f0' },
  headerTitle: { fontSize: '18px', fontWeight: '700', color: '#0f172a', margin: 0, letterSpacing: '-0.02em' },
  badgeCount: { fontSize: '12px', fontWeight: '600', color: '#475569', backgroundColor: '#f1f5f9', padding: '4px 10px', borderRadius: '20px', marginLeft: '10px' },
  actionBar: { display: 'flex', gap: '12px', alignItems: 'center' },
  btnSecondary: { display: 'flex', gap: '6px', alignItems: 'center', backgroundColor: '#ffffff', border: '1px solid #e2e8f0', color: '#334155', padding: '8px 16px', borderRadius: '8px', fontSize: '13px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.2s ease', boxShadow: '0 1px 2px rgba(0, 0, 0, 0.05)' },
  btnDeleteBulk: { display: 'flex', gap: '6px', alignItems: 'center', backgroundColor: '#fef2f2', border: '1px solid #fecaca', color: '#dc2626', padding: '8px 16px', borderRadius: '8px', fontSize: '13px', fontWeight: '600', cursor: 'pointer', transition: 'all 0.2s ease' },
  searchInputWrapper: { position: 'relative', display: 'flex', alignItems: 'center' },
  searchInput: { width: '260px', padding: '8px 12px 8px 36px', border: '1px solid #e2e8f0', borderRadius: '8px', fontSize: '13px', backgroundColor: '#f8fafc', color: '#0f172a', outline: 'none', transition: 'all 0.2s ease' },
  statsContainer: { padding: '24px 24px 0' },
  statsGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '16px' },
  statCard: { backgroundColor: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '12px', padding: '20px', boxShadow: '0 1px 3px rgba(0,0,0,0.02), 0 1px 2px rgba(0,0,0,0.04)', position: 'relative', overflow: 'hidden' },
  statCardLabel: { fontSize: '11px', fontWeight: '600', textTransform: 'uppercase', color: '#64748b', letterSpacing: '0.05em', marginBottom: '8px' },
  statCardValue: { fontSize: '28px', fontWeight: '700', color: '#0f172a', lineHeight: '1.2' },
  gridContainer: { padding: '24px', flex: 1, overflowY: 'auto' },
  tableWrapper: { backgroundColor: '#ffffff', border: '1px solid #e2e8f0', borderRadius: '12px', overflow: 'hidden', boxShadow: '0 1px 3px rgba(0,0,0,0.02), 0 1px 2px rgba(0,0,0,0.04)' },
  table: { width: '100%', borderCollapse: 'collapse', textAlign: 'left' },
  th: { backgroundColor: '#f8fafc', color: '#475569', fontWeight: '600', fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.05em', padding: '14px 16px', borderBottom: '1px solid #e2e8f0' },
  td: { padding: '14px 16px', borderBottom: '1px solid #f1f5f9', color: '#334155', fontSize: '13px', verticalAlign: 'middle' },
  badgeInbound: { display: 'inline-flex', padding: '3px 8px', borderRadius: '20px', fontSize: '10px', fontWeight: '700', backgroundColor: '#eff6ff', color: '#2563eb', border: '1px solid #bfdbfe', textTransform: 'uppercase', letterSpacing: '0.03em' },
  badgeOutbound: { display: 'inline-flex', padding: '3px 8px', borderRadius: '20px', fontSize: '10px', fontWeight: '700', backgroundColor: '#ecfdf5', color: '#059669', border: '1px solid #a7f3d0', textTransform: 'uppercase', letterSpacing: '0.03em' },
  statusBadge: { display: 'inline-flex', alignItems: 'center', gap: '6px', padding: '4px 10px', borderRadius: '20px', fontSize: '11px', fontWeight: '600' },
  drawerBackdrop: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(15, 23, 42, 0.4)', backdropFilter: 'blur(4px)', display: 'flex', justifyContent: 'flex-end', zIndex: 9999 },
  
  // ─── OPTIMIZED WIDTH: INCREASED HORIZONTAL SPACE PROFILE DIMENSIONS ─────
  drawerPanel: { width: '850px', height: '100%', background: '#ffffff', boxShadow: '-10px 0 30px rgba(0,0,0,0.08)', padding: '28px', display: 'flex', flexDirection: 'column', overflowY: 'auto' },
  // ─────────────────────────────────────────────────────────────────────────
  
  drawerHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '20px' },
  drawerTitle: { fontSize: '16px', fontWeight: '700', color: '#0f172a', marginTop: '10px', marginBottom: '4px', wordBreak: 'break-all', fontFamily: 'monospace', letterSpacing: '-0.01em' },
  closeBtn: { background: '#f1f5f9', border: 'none', borderRadius: '50%', padding: '8px', cursor: 'pointer', color: '#64748b', display: 'flex', transition: 'background-color 0.2s' },
  tabBar: { display: 'flex', gap: '8px', borderBottom: '1px solid #e2e8f0', marginBottom: '24px' },
  tabButtonActive: { background: 'none', border: 'none', borderBottom: '2px solid #2563eb', color: '#2563eb', fontWeight: '600', fontSize: '13px', padding: '10px 16px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.2s' },
  tabButtonInactive: { background: 'none', border: 'none', borderBottom: '2px solid transparent', color: '#64748b', fontWeight: '500', fontSize: '13px', padding: '10px 16px', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: '8px', transition: 'all 0.2s' },
  detailCard: { border: '1px solid #e2e8f0', borderRadius: '10px', padding: '18px', backgroundColor: '#f8fafc', marginBottom: '16px' },
  detailCardHeader: { display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px', borderBottom: '1px solid #e2e8f0', paddingBottom: '10px' },
  detailCardTitle: { fontSize: '13px', fontWeight: '700', margin: 0, color: '#1e293b', textTransform: 'uppercase', letterSpacing: '0.03em' },
  detailTable: { width: '100%', fontSize: '12px', borderCollapse: 'collapse' },
  detailLabel: { padding: '6px 0', color: '#64748b', width: '150px', fontWeight: '500' },
  detailValue: { padding: '6px 0', fontWeight: '600', color: '#0f172a' },
  terminalLog: { flex: 1, background: '#09090b', color: '#e4e4e7', padding: '18px', borderRadius: '8px', fontSize: '11px', fontFamily: 'Consolas, Monaco, monospace', lineHeight: '1.6', overflow: 'auto', border: '1px solid #27272a', minHeight: '400px', whiteSpace: 'pre-wrap' }
};

export default TransactionLedger;